# Generated by Django 5.0.2 on 2024-05-19 17:51

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(verbose_name=django.db.models.fields.AutoField),
        ),
    ]
