# Generated by Django 5.0.2 on 2024-05-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
