# Generated by Django 5.0.2 on 2024-05-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='brand',
        ),
    ]
