# Generated by Django 5.0.2 on 2024-05-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shirt',
        ),
    ]
