# Generated by Django 5.0.2 on 2024-05-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='suggestions',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
